- name: Deploy to ECS
  hosts: local
  connection: local
  tasks: 
  - name: Create task definition
    community.aws.ecs_taskdefinition:
       family: dev
       containers:
       - name: petclinic
         essential: true
         image: "{{ image }}"
         portMappings:
         - containerPort: 8080
           hostPort: 8080
       launch_type: EC2  
       ec2_region: eu-central-1
       aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
       aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
       memory: 512
       network_mode: awsvpc
       state: present

  - name: Run task
    community.aws.ecs_task:
       operation: run
       cluster: developer
       task_definition: dev
       count: 1
       started_by: ansible_user
         
